### ISSUE TITLE
Suggestion for new color palettes. 🎨

### ISSUE THREAD

**Issue by alicemsu** [VermeilChan/MetalSlugFontRebornWeb#2]
Could you please update the new color palettes recently added by division 6?

https://6th-divisions-den.com/rip_info/MS_Typewriter_v2.zip

Thank you, great contribution and tool.

**Comment by VermeilChan** [comment]
While it's a good idea, I'm not going to be adding them, sadly. It takes a lot of time and is not something I really like doing.
but I might add them in future
