### ISSUE TITLE
Problem with the paired symbols ✏️

### ISSUE THREAD

**Issue by alicemsu** [VermeilChan/MetalSlugFontRebornWeb#3]
There is a problem with the paired symbols. When typing "(" to generate it, ")" is displayed, and vice versa.
![Screenshot_2024-05-07-00-36-30-738_com android chrome-edit](https://github.com/VermeilChan/MetalSlugFontRebornWeb/assets/106787183/55c2ad7a-3413-4f01-8343-a930919678a6)
![Screenshot_2024-05-07-00-36-19-248_com android chrome-edit](https://github.com/VermeilChan/MetalSlugFontRebornWeb/assets/106787183/b519e4c2-9ce2-4542-bf87-06d4ba20a95b)
![Image_1715060295909](https://github.com/VermeilChan/MetalSlugFontRebornWeb/assets/106787183/8ebc1ef2-5bdd-4770-b14a-033f2cc41c6a)

**Comment by VermeilChan** [comment]
thanks for the report :)

**Comment by VermeilChan** [comment]
fixed :)
try now
