### ISSUE TITLE
Character support to expand the multilingual capabilities of font 1 ✏️

### ISSUE THREAD

**Issue by alicemsu** [VermeilChan/MetalSlugFontRebornWeb#4]
All the characters are cropped at size x4, so I hope they can be added successfully.
Sent in 3 different color palettes:

[bluefont1ms-x4.zip](https://github.com/user-attachments/files/16737596/bluefont1ms-x4.zip)
[goldfont1ms-x4.zip](https://github.com/user-attachments/files/16737597/goldfont1ms-x4.zip)
[orangefont1ms-x4.zip](https://github.com/user-attachments/files/16737599/orangefont1ms-x4.zip)

äëïöüÿ āōēīū áéíóú âêîôû àèìòù ǎǒěǐǔ çæœ ãõñ ȧė ÄËÏÖÜŸ ĀŌĒĪŪ ÁÉÍÓÚ ÂÊÎÔÛ ÀÈÌÒÙ ǍǑĚǏǓ ÇÆŒ ÃÕÑ ȦĖ £ ß ® @ € » « ¿ ¡ º ª ÷ ¬ | ♪ ǖǘǚǜ ǕǗǙǛ

Note: I haven't renamed each character because I'm unsure how you'll be adding them.

![other](https://github.com/user-attachments/assets/2ead1499-d6b5-4efe-92f7-9d02ecdfad6c)

**Comment by VermeilChan** [comment]
I actually tried to add support for these, but when you attempt to generate them, it doesn't detect the correct character. I don't remember exactly, but for example, I tried to generate 'à,' and it only detected the ` symbol. I don't think it's going to be a fun process, especially the coding part. sorry :(

**Comment by alicemsu** [comment]
It is very sad, but thank you for the response. Hopefully, the option to write on a new line can be added in the future. By the way, in font 1 the letter "o" is poorly cut. Regards.

**Comment by alicemsu** [comment]
https://github.com/VermeilChan/MetalSlugFontRebornWeb/blob/main/src/static/assets/fonts/font-1/ms-blue/letters/lower-case/o.png

**Comment by alicemsu** [comment]
It is very sad, but thank you for the response. Hopefully, the option to write on a new line can be added in the future. By the way, in font 1 the letter "o" is poorly cut. Regards.

https://github.com/VermeilChan/MetalSlugFontRebornWeb/blob/main/src/static/assets/fonts/font-1/ms-blue/letters/lower-case/o.png

**Comment by VermeilChan** [comment]
> It is very sad, but thank you for the response. Hopefully, the option to write on a new line can be added in the future. By the way, in font 1 the letter "o" is poorly cut. Regards.
> 
> https://github.com/VermeilChan/MetalSlugFontRebornWeb/blob/main/src/static/assets/fonts/font-1/ms-blue/letters/lower-case/o.png

I'll fix it! :) Also, can you explain how to implement the option for writing a new line? Specifically, how should I determine when to create a new line? Should it be based on reaching a specific pixel width or another factor?

**Comment by VermeilChan** [comment]
> It is very sad, but thank you for the response. Hopefully, the option to write on a new line can be added in the future. By the way, in font 1 the letter "o" is poorly cut. Regards.
> 
> https://github.com/VermeilChan/MetalSlugFontRebornWeb/blob/main/src/static/assets/fonts/font-1/ms-blue/letters/lower-case/o.png

it might take sometime for the web version to get the line break tho, i dont really like writing html code :(
